name: Build

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: Checkout builds
        uses: actions/checkout@v4
        with:
          ref: "builds"
          path: "builds"

      - name: Clean old builds
        run: rm $GITHUB_WORKSPACE/builds/*.cs3 || true

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 11076708
          packages: 'platform-tools'
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: false

      - name: Accept remaining licenses
        run: yes | sdkmanager --licenses || true

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew

          # Try to build. If no plugins are enabled, don't fail.
          ./gradlew make makePluginsJson --stacktrace || true

          # Always make sure the builds folder and plugins.json exist
          mkdir -p $GITHUB_WORKSPACE/builds
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds 2>/dev/null || true
          cp build/plugins.json $GITHUB_WORKSPACE/builds 2>/dev/null || true

          # Create an empty plugins.json if it doesn't exist
          if [ ! -f $GITHUB_WORKSPACE/builds/plugins.json ]; then
            echo "[]" > $GITHUB_WORKSPACE/builds/plugins.json
          fi

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "Build $GITHUB_SHA" || exit 0
          git push --force